/*
This problem is a programming version of Problem 45 from projecteuler.net

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae: 
Triangle		Tn=n(n+1)/2		1,3,6,10,15,...	
Pentagonal		Pn=n(3n-1)/2	1,5,12,22,35,...
Hexagonal		Hn=n(2n-1)		1,6,15,28,45,...

It can be verified that T285=P165=H143=40755

For this challene you are given N, a, b, where a<b and a,bE{3,5,6} 
where 3 represents triangular numbers, 5 represents pentagonal numbers and 6 is hexagonal. It can be observed that all hexagonal numbers are triangular numbers so we'll handle only 2 kinds of queries as 
N 3 5, find all numbers below N which are Triangular number as well as Pentagonal 
N 5 6, find all numbers below N which are Pentagonal number as well as Hexagonal

Input Format 
Input contains three integers N a b

Output Format 
Print the answer corresponding to the test case. Print numbers in ascending oder.

Constraints 
2<=N<=2×10^14 
a,bE{3,5,6} 
a<b

Sample Input #00
10000 3 5

Sample Output #00
1
210

Sample Input #01
100000 5 6

Sample Output #01
1
40755
*/

#include<stdio.h>
#include<math.h>


int tri(unsigned long long int n)
{
	unsigned long long int a;
	long long int b;
	double d;
	d = sqrt(1+8*n);
	d = (d-1)/2;
	b = (long long int)d;
	a = b*(b+1)/2;
	if(a==n)
	{
		return 1;
	}
	else
	{
		return 0;
	}
}

int pen(unsigned long long int n)
{
	unsigned long long int a;
	long long int b;
	double d;
	d = sqrt(1+24*n);
	d = (d+1)/6;
	b = (long long int)d;
	a = b*(3*b-1)/2;
	if(a==n)
	{
		return 1;
	}
	else
	{
		return 0;
	}
}

int hex(unsigned long long int n)
{
	unsigned long long int a;
	long long int b;
	double d;
	d = sqrt(1+8*n);
	d = (d+1)/4;
	b = (long long int)d;
	a = b*(2*b-1);
	if(a==n)
	{
		return 1;
	}
	else
	{
		return 0;
	}
}

int main()
{
	int a,b;
	unsigned long long int y,x,i,n;
	scanf("%llu%d%d",&n,&a,&b);
	x = 0;
	if(b==5)
	{
		for(i=1;x<n;i++)
		{
			x = i*(3*i-1)/2;
			if(x>=n)
			{
				continue;
			}
			y = tri(x);
			if(y==1)
			{
				printf("%llu\n",x);
			}
		}	
	}
	else if(b==6)
	{
		for(i=1;x<n;i++)
		{
			x = i*(2*i-1);
			if(x>=n)
			{
				continue;
			}
			y = pen(x);
			if(y==1)
			{
				printf("%llu\n",x);
			}
		}	
	}
	return 0;
}
